# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9b32e836473218f6b1ebafac30d6a1f75f3e5c7fee27cef18c2eb91b4d3ebbfd81255cea18c69f09c04c09ea26bf6211a76afc0f7c791a00cece299ffa8245d

test:
  secret_key_base: 26d02288c6ba75e849d3920099cea0d18c2d41b76254d2985b8d601c93c96b76b85c7c0fcb3072c50bf44a206b9608cdb0fa8fd3147467a2db9bb1066db3957a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
